[package]
name = "gravily"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
image = "0.25.9"
ratatui = "0.29.0"
termimage = "1.2.2"
tui-input = "0.14.0"
whoami = "1.6.1"
